PACKAGE_NAME="motu424"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="motu424"
BUILT_MODULE_LOCATION[0]="kernel"
DEST_MODULE_LOCATION[0]="/kernel/sound/pci"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/kernel modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/kernel clean"
AUTOINSTALL="yes"
